//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealStatus
    {
        public DealStatus()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int DealStatusID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
