//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapDealAnalyst
    {
        public Nullable<int> DealID { get; set; }
        public Nullable<int> AnalystID { get; set; }
        public int MapDealAnalystID { get; set; }
        public Nullable<bool> IsLeadAnalyst { get; set; }
    
        public virtual Analyst Analyst { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
