//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergerArbNew
    {
        public Nullable<System.DateTime> Field_Updated { get; set; }
        public string Field_Type { get; set; }
        public string Field_Name { get; set; }
        public string Calendar_Flag { get; set; }
        public string Field_Value { get; set; }
        public string Calendar_Time { get; set; }
        public string Calendar_Comment { get; set; }
        public Nullable<int> DealId { get; set; }
        public int ID { get; set; }
    }
}
