//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergerArb
    {
        public int C000_DealId__Required_ { get; set; }
        public string C001_Deal_Name__Required_ { get; set; }
        public string C002_Target_Ticker__Required_ { get; set; }
        public string C003_Target_Name__Required_ { get; set; }
        public string C004_Acquirer_Ticker__Required_ { get; set; }
        public string C005_Acquirer_Name__Required_ { get; set; }
        public string C006_File_Name_Path__Required_ { get; set; }
        public string C008_Target_Shares_Owned__Required_ { get; set; }
        public string C009_Acquirer_Shares_Owned__Required_ { get; set; }
        public string C011_Key_Notes_1__Required_ { get; set; }
        public string C012_Key_Notes_2__Required_ { get; set; }
        public string C013_Key_Notes_3__Required_ { get; set; }
        public string C014_Pricing_Period__Required_ { get; set; }
        public string C015_Target_Earnings_Date__Required_ { get; set; }
        public string C016_Acquirer_Earnings_Date__Required_ { get; set; }
        public string C017_Key_Dates__Required_ { get; set; }
        public string C019_Stated_Cash_Terms__Optional_ { get; set; }
        public string C020_Stated_Stock_Exchange_Ratio__Optional_ { get; set; }
        public string C021_Cash_Prorate__Optional_ { get; set; }
        public string C022_Stock_Prorate__Optional_ { get; set; }
        public string C023_Hedge_Ratio__Required_ { get; set; }
        public string C024_Cash_Terms__Required_ { get; set; }
        public string C025_Stock_Exchange_Ratio__Required_ { get; set; }
        public string C027_Target_Price_in_Local_Currency__Required_ { get; set; }
        public string C028_Acquirer_Price_in_Local_Currency__Required_ { get; set; }
        public string C029_Target_Price_in_Deal_Currency__Required_ { get; set; }
        public string C030_Acquirer_Price_in_Deal_Currency__Required_ { get; set; }
        public string C032_Target_Currency__Required_ { get; set; }
        public string C033_Acquirer_Currency__Required_ { get; set; }
        public string C034_Deal_Currency__Required_ { get; set; }
        public string C035_FX_Ratio_to_Convert_to_Target_Acquirer_into_Deal_Currency__Required_ { get; set; }
        public string C036_FX_Ratio_to_Convert_to_Target_Price_into_Deal_Currency__Required_ { get; set; }
        public string C037_FX_Ratio_to_Covert_Deal_Currency_to_USD__Optional_ { get; set; }
        public string C039_Today__Optional_ { get; set; }
        public string C040_Announced_Date__Required_ { get; set; }
        public string C041_Estimated_Close_Date__Optional_ { get; set; }
        public string C042_Potential_Days_Delayed__Optional_ { get; set; }
        public string C043_Days_to_Close__Optional_ { get; set; }
        public string C044_Close_Date__Required_ { get; set; }
        public string C046_Total_Consideration__Optional_ { get; set; }
        public string C047_Gross_Spread__Required_ { get; set; }
        public string C048_Net_Spread_before_Leverage__Required_ { get; set; }
        public string C049_Cost_of_Leverage__Optional_ { get; set; }
        public string C050_Net_Dividends__Required_ { get; set; }
        public string C051_Short_Rebates__Optional_ { get; set; }
        public string C052_Net_Spread__Required_ { get; set; }
        public string C053_Hypothetical_Targeted_Net_Spread__Required_ { get; set; }
        public string C054_Hypothetical_Unwind_Net_Spread__Required_ { get; set; }
        public string C055_Theoretical_Spread_collar__Required_ { get; set; }
        public string C057_Gross_Return__Optional_ { get; set; }
        public string C058_Annualized_ROR__Required_ { get; set; }
        public string C059_Hypothetical_Targeted_Annualized_Return__Required_ { get; set; }
        public string C060_Hypothetical_Unwind_Annualized_Return__Required_ { get; set; }
        public string C061_Theoretical_Annualized_Return_collar__Required_ { get; set; }
        public string C063_Commission_Cost_per_Share__Optional_ { get; set; }
        public string C064_Long_Financing_Rate__Optional_ { get; set; }
        public string C065_Short_Rebate__Optional_ { get; set; }
        public string C066_Long_Margin_Required__Optional_ { get; set; }
        public string C067_Short_Margin_Required__Optional_ { get; set; }
        public string C069_Target_Ex_Dividend_Date__Required_ { get; set; }
        public string C070_Aquirer_Ex_Dividend_Date__Required_ { get; set; }
        public string C071_Target_Dividend_Projected_or_Declared__Required_ { get; set; }
        public string C072_Acquirer_Dividend_Projected_or_Declared__Required_ { get; set; }
        public string C073_Number_of_Target_Dividends__Required_ { get; set; }
        public string C074_Number_of_Acquirer_Dividends__Required_ { get; set; }
        public string C075_Target_Dividend_Quarterly_Amount__Required_ { get; set; }
        public string C076_Acquirer_Dividend_Quarterly_Amount__Required_ { get; set; }
        public string C077_Total_Target_Dividends__Required_ { get; set; }
        public string C078_Total_Acquirer_Dividends__Required_ { get; set; }
        public string C080_Target_Break_Price__Required_ { get; set; }
        public string C081_Acquirer_Break_Price__Required_ { get; set; }
        public string C082_Expected_USD_Return_prob_wtd__Required_ { get; set; }
        public string C083_RiskReward__Required_ { get; set; }
        public string C084_Notional_Long_USD_MV__Required_ { get; set; }
        public string C085_Net_USD_Profit_at_Close__Required_ { get; set; }
        public string C086_Net_USD_Profit_at_Break__Required_ { get; set; }
        public string C087_Probability_of_Break__Required_ { get; set; }
        public string C088_Tgt_13D_Num_shs_remaining__Optional_ { get; set; }
        public string C090_Prorate_Value_of_Stock__Optional_ { get; set; }
        public string C091_Prorate_Value_of_Cash__Optional_ { get; set; }
        public string C092_Prorate_Comment_1__Optional_ { get; set; }
        public string C093_Prorate_Comment_2__Optional_ { get; set; }
        public string C095_Collar_Flag_Yes_No__Optional_ { get; set; }
        public string C096_Collar_Flag_Normal_Inverted__Optional_ { get; set; }
        public string C097_Collar_Num_of_Segments__Optional_ { get; set; }
        public string C098_Collar_Num_of_Breakpoints__Optional_ { get; set; }
        public string C099_Collar___Optional_ { get; set; }
        public string C100_Collar_High_Breakpoint__Optional_ { get; set; }
        public string C101_Collar_Position__Optional_ { get; set; }
        public string C102_Collar_Walk__Optional_ { get; set; }
        public string C103_Collar_Cure_Low_Breakpoint__Optional_ { get; set; }
        public string C104_Collar_Cure_High_Breakpoint__Optional_ { get; set; }
        public string C105_Collar_Value_of_Collar__Optional_ { get; set; }
        public string C106_Collar_Note_Description__Optional_ { get; set; }
        public string C108_Pricing_Period_Start_Date__Optional_ { get; set; }
        public string C109_Pricing_Period_End_Date__Optional_ { get; set; }
        public string C110_Pricing_Period_Length_days__Optional_ { get; set; }
        public string C111_Pricing_Period_Trading_Days_Prior_to_Close___Optional_ { get; set; }
        public string C112_Pricing_Period_Prc_Complete__Optional_ { get; set; }
        public string C113_Pricing_Period_Prc_Remaining__Optional_ { get; set; }
        public string C114_Pricing_Period_Price_Based_on_Prc_Complete__Optional_ { get; set; }
        public string C115_Pricing_Period_Price_Based_on_Prc_Remaining__Optional_ { get; set; }
        public string C116_Pricing_Period_Weighted_Price__Optional_ { get; set; }
        public string C118_Bloomberg_Corporate_Action_ID__Optional_ { get; set; }
        public string C119_Bloomberg_Target_Company_Description__Optional_ { get; set; }
        public string C120_Bloomberg_Acquirer_Company_Description__Optional_ { get; set; }
        public string C121_Bloomberg_Deal_Description__Optional_ { get; set; }
        public string C122_Bloomberg_Target_Legal_Advisors__Optional_ { get; set; }
        public string C123_Bloomberg_Target_Financial_Advisors__Optional_ { get; set; }
        public string C124_Bloomberg_Acquirer_Legal_Advisors__Optional_ { get; set; }
        public string C125_Bloomberg_Acquirer_Financial_Advisors__Optional_ { get; set; }
        public string C126_Bloomberg_Pending_Approvals__Optional_ { get; set; }
        public string C127_Bloomberg_Approved_Approvals__Optional_ { get; set; }
        public string C128_Bloomberg_Expired_Approvals__Optional_ { get; set; }
        public string C129_Bloomberg_Entended_Approvals__Optional_ { get; set; }
        public string C130_Bloomberg_Announced_Date__Optional_ { get; set; }
        public string C131_Bloomberg_Amendment_Date__Optional_ { get; set; }
        public string C132_Bloomberg_Expected_Completion_Date__Optional_ { get; set; }
        public string C133_Bloomberg_Completed_Termination_Date__Optional_ { get; set; }
        public string C134_Bloomberg_Merger_Agreement_Date__Optional_ { get; set; }
        public string C135_Bloomberg_Drop_Dead_Date__Optional_ { get; set; }
        public string C136_Bloomberg_Go_Shop_Period_Start_Date__Optional_ { get; set; }
        public string C137_Bloomberg_Go_Shop_Period_End_Date__Optional_ { get; set; }
        public int MergerArbID { get; set; }
    }
}
