//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public int SecurityID { get; set; }
        public decimal Price1 { get; set; }
        public System.DateTime PriceDateTime { get; set; }
        public string PriceSource { get; set; }
    
        public virtual Security Security { get; set; }
    }
}
