//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortexWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DealSecPrice
    {
        public string Description { get; set; }
        public int DealID { get; set; }
        public Nullable<int> SecurityGroupID { get; set; }
        public Nullable<decimal> TargetPrice { get; set; }
        public Nullable<decimal> DownsidePrice { get; set; }
        public string Comps { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Code { get; set; }
        public int SecGrp { get; set; }
        public int SecurityID1 { get; set; }
        public int SecurityID { get; set; }
        public int PricSec { get; set; }
        public decimal CurrentPrice { get; set; }
    }
}
