//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibraryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int DealID { get; set; }
        public string Description { get; set; }
        public Nullable<int> SecurityGroupID { get; set; }
        public Nullable<int> CompanyID1 { get; set; }
        public Nullable<int> CompanyID2 { get; set; }
        public Nullable<int> CompanyID3 { get; set; }
        public string InvestmentThesis { get; set; }
        public Nullable<int> MergerAgreementEventID { get; set; }
        public Nullable<int> DropDeadEventID { get; set; }
        public Nullable<int> TargetShareholderMeetingEventID { get; set; }
        public Nullable<int> AcquirerShareholderMeetingEventID { get; set; }
        public Nullable<decimal> TargetPrice { get; set; }
        public string Recommendation { get; set; }
        public Nullable<int> DealCurrencyID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> DocumentGroupID { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Company Company2 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Event Event { get; set; }
        public virtual Event Event1 { get; set; }
        public virtual Event Event2 { get; set; }
        public virtual Event Event3 { get; set; }
        public virtual DocumentGroup DocumentGroup { get; set; }
        public virtual SecurityGroup SecurityGroup { get; set; }
    }
}
