//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibraryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentGroup
    {
        public DocumentGroup()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int DocumentGroupID { get; set; }
        public int DocumentID1 { get; set; }
        public Nullable<int> DocumentID2 { get; set; }
        public Nullable<int> DocumentID3 { get; set; }
    
        private ICollection<Deal> Deals { get; set; }
        private Document Document { get; set; }
        private Document Document1 { get; set; }
        private Document Document2 { get; set; }
    }
}
