//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibraryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityType
    {
        public SecurityType()
        {
            this.Securities = new HashSet<Security>();
        }
    
        public int SecurityTypeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        private ICollection<Security> Securities { get; set; }
    }
}
